//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitaye.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quitaye.Res.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceuil.
        /// </summary>
        internal static string Acceuil {
            get {
                return ResourceManager.GetString("Acceuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        internal static string Catégories {
            get {
                return ResourceManager.GetString("Catégories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un projet.
        /// </summary>
        internal static string Creer_Projet {
            get {
                return ResourceManager.GetString("Creer_Projet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gammes.
        /// </summary>
        internal static string Gammes {
            get {
                return ResourceManager.GetString("Gammes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison.
        /// </summary>
        internal static string Livraison {
            get {
                return ResourceManager.GetString("Livraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque.
        /// </summary>
        internal static string Marques {
            get {
                return ResourceManager.GetString("Marques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière_Première.
        /// </summary>
        internal static string Matière {
            get {
                return ResourceManager.GetString("Matière", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer votre premier projet.
        /// </summary>
        internal static string Message_Acceuil_Affichage {
            get {
                return ResourceManager.GetString("Message_Acceuil_Affichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veillez ajouter des données pour afficher.
        /// </summary>
        internal static string Message_Tableau_Vide {
            get {
                return ResourceManager.GetString("Message_Tableau_Vide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payement.
        /// </summary>
        internal static string Payement {
            get {
                return ResourceManager.GetString("Payement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string Productions {
            get {
                return ResourceManager.GetString("Productions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit Finis.
        /// </summary>
        internal static string Produit_Finis {
            get {
                return ResourceManager.GetString("Produit_Finis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée à affiché.
        /// </summary>
        internal static string Table_Vide {
            get {
                return ResourceManager.GetString("Table_Vide", resourceCulture);
            }
        }
    }
}
